### PR TITLE
Version 1.1-alpha2

### PR DESCRIPTION
**Pull request by thefrosty**
It's a good starting point. I've cleaned up some spelling errors and code infractions. I've also used better code standards with dependency injection when there is not need to extend a class.

### CODE REVIEW

**Comment by aristath** [comment]
Hey there!

I didn't realize anyone was using this...
Thank you! merged. :+1:

**Comment by thefrosty** [comment]
Super quick response. ;)

I've been using a slightly modified version of the original I acquired a while back  and happened to see your copy today. Made some initial adjustments and plan to make some more. 

👍🏼

**Comment by aristath** [comment]
I could just make you an admin on this one and we can work together on this project... Truth is it needs some lovin' and I've been busy with another project so this one got left behind.

Would something like that interest you?
A free product like this is something that's missing in the EDD community...

**Comment by thefrosty** [comment]
Sure!

**Comment by aristath** [comment]
Awesome!

You should now have full access :+1:

**Comment by thefrosty** [comment]
Before I submit another PR and move development to this branch I wanted to show you what I did, and how I changed up the format of this plugin. Check out https://github.com/thefrosty/edd-remote-installer

**Comment by aristath** [comment]
Nice!! I like it!

**Pull request merged**
